#!/bin/sh

if [ -n "$*" ]
then
    # If command line arguments are given, use them
    exec mono /usr/lib/ckan/ckan.exe "$@"
else
    # No command line arguments
    if [ -n "$WAYLAND_DISPLAY" -o -n "$DISPLAY" ]
    then
        # Default to the native Linux GUI if available
        if [ -x /usr/bin/ckan-linux ]
        then
            exec /usr/bin/ckan-linux
        else
            exec mono /usr/lib/ckan/ckan.exe gui
        fi
    else
        # Run the retro text UI if graphics aren't available
        exec mono /usr/lib/ckan/ckan.exe consoleui
    fi
fi
